Importação das bibliotecas

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

Carregamento da base de dados

In [ ]:
iris = pd.read_csv('iris.csv')
iris['class'].value_counts()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
x, _, y, _ = train_test_split(
  iris.iloc[:,:4],
  iris.iloc[:, 4],
  test_size=0.5,
  stratify=iris.iloc[:, 4]
)
y.value_counts()

class
Iris-versicolor    25
Iris-virginica     25
Iris-setosa        25
Name: count, dtype: int64

Carregamento da base de dados e contagem de quantos registros por classe

In [ ]:
infert = pd.read_csv('infert.csv')
infert

,Unnamed: 0,education,age,parity,induced,case,spontaneous,stratum,pooled.stratum
0,1,0-5yrs,26,6,1,1,2,1,3
1,2,0-5yrs,42,1,1,1,0,2,1
2,3,0-5yrs,39,6,2,1,0,3,4
3,4,0-5yrs,34,4,2,1,0,4,2
4,5,6-11yrs,35,3,1,1,1,5,32
...,...,...,...,...,...,...,...,...,...
243,244,12+ yrs,31,1,0,0,1,79,45
244,245,12+ yrs,34,1,0,0,0,80,47
245,246,12+ yrs,35,2,2,0,0,81,54
246,247,12+ yrs,29,1,0,0,1,82,43
247,248,12+ yrs,23,1,0,0,1,83,40

In [ ]:
infert['education'].value_counts()

education
6-11yrs    120
12+ yrs    116
0-5yrs      12
Name: count, dtype: int64

In [ ]:
x1, _, y1, _ = train_test_split(
  infert.iloc[:,2:9],
  infert.iloc[:, 1],
  test_size=0.6,
  stratify=infert.iloc[:, 1]
)
y1.value_counts()

education
6-11yrs    48
12+ yrs    46
0-5yrs      5
Name: count, dtype: int64